services:
  host_app:
    container_name: federation_host_app
    build:
      context: docker/services/federated_app
    ports:
      - "5180:5180"
    volumes:
      - type: bind
        source: ./host_app
        target: /home/node/app

  app_one:
    container_name: federation_app_one
    build:
      context: docker/services/federated_app
    ports:
      - "5181:5181"
    volumes:
      - type: bind
        source: ./app_one
        target: /home/node/app

  app_two:
    container_name: federation_app_two
    build:
      context: docker/services/federated_app
    ports:
      - "5182:5182"
    volumes:
      - type: bind
        source: ./app_two
        target: /home/node/app

